### Example: Creating and Running a Race

# Create a user
POST http://localhost:8080/user/create
Content-Type: application/json

{
  "username": "champ",
  "balance": 1000
}

###

# Get user details
GET http://localhost:8080/user/1

###

# Create a race
POST http://localhost:8080/race/create

###

# Get race details
GET http://localhost:8080/race/1

###

# Place a bet (race must be in CREATED status)
POST http://localhost:8080/bet/place
Content-Type: application/json

{
  "userId": 1,
  "raceId": 1,
  "carId": 2,
  "amount": 100
}

###

# Start the race
POST http://localhost:8080/race/1/start

###

# Join race (for WebSocket validation)
POST http://localhost:8080/race/1/join

###

# Check race status while running
GET http://localhost:8080/race/1

###

# After race finishes, check user balance
GET http://localhost:8080/user/1

###

# Create another user for testing
POST http://localhost:8080/user/create
Content-Type: application/json

{
  "username": "net",
  "balance": 1000000
}

###

# Create multiple races
POST http://localhost:8080/race/create

###
POST http://localhost:8080/race/create

###
POST http://localhost:8080/race/create
